from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', home, name='home'),
    path('register/',register_view,name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('products/add-product/', add_product, name='add_product'),
    path('products/edit/<int:pk>/', edit_product, name='edit_product'),
    path('products/', product_list, name='product_list'),
    path('category/<slug:slug>/', product_list_by_category, name='products_by_category'),
    path('product/<int:id>/', product_detail, name='product_detail'),
    path('productslist/', products, name='products'),
    path('productslist/<int:category_id>/', products, name='products'),
    path('categories/', category_user, name='category_user'),
    path('categorie/', category_list, name='category_list'),
    path('category/<slug:slug>/', category_detail, name='category_detail'),
    path('categories/add/', add_category, name='add_category'),
    path('brands/', brand_list, name='brand_list'),
    path('brands/add/', add_brand, name='add_brand'),
    path('brands/edit/<int:brand_id>/', edit_brand, name='edit_brand'),
    path('brands/delete/<int:brand_id>/', delete_brand, name='delete_brand'),
    path('orders/', order_list, name='order_list'),
    path('orders/<str:order_id>/', order_detail, name='order_detail'),
    path('admins/reports/', reports_dashboard, name='reports_dashboard'),
    path('admins/customers/', customers_list, name='customers_list'),
    path('my-account/', my_account, name='my_account'),
    path('wishlist/', account_view, name='wishlist'),
    path('wishlist/remove/<int:wishlist_id>/', remove_wishlist, name='remove_wishlist'),
    path('cart/', cart_view, name='cart_view'),
    path('cart/add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('profile/', personal_info_view, name='personal_info'),
    path('returns/', returns_view, name='returns'),
    path('settings/', settings_view, name='settings'),
    path('cart/', cart_view, name='cart'),
    path('checkout/', checkout, name='checkout'),
    path('apply-coupon/', apply_coupon, name='apply_coupon'),
    path('cart/update/', update_cart, name='update_cart'),
    path('clear-cart/', clear_cart, name='clear_cart'),
    path('order-success/', order_success, name='order_success'),
    path('place-order/', place_order, name='place_order'),
    path('wishlist/add/<int:product_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('api/products/', ProductListCreateAPIView.as_view(), name='product-list-create'),
    path('api/products/<int:id>/', ProductRetrieveUpdateDestroyAPIView.as_view(), name='product-detail'),
]
