# Generated by Django 5.2.1 on 2025-05-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionApp', '0002_address_category_notification_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
