# Generated by Django 5.2.1 on 2025-05-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionApp', '0004_wishlist_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
