# Generated by Django 5.1.7 on 2025-05-20 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionApp', '0005_userprofile_birthdate_userprofile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.BooleanField(default=True)),
                ('shipping_updates', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('password_changes', models.BooleanField(default=True)),
                ('promotions', models.BooleanField(default=False)),
                ('new_products', models.BooleanField(default=False)),
                ('recommendations', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
