# Generated by Django 5.1.7 on 2025-05-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionApp', '0012_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
